{
  "swagger": "2.0",
  "info": {
    "title": "Positioning API",
    "version": "1.8.0",
    "description": "Positioning API for making location requests.",
    "x-document-meta-data": {
      "copyright": "Â© 2020 HERE Europe B.V.",
      "document-id": "34f42f6d-f383-435b-af45-155bc5e120dd",
      "date-created": "2020-01-15T05:16:12+00:00"
    }
  },
  "host": "pos.api.here.com",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "parameters": {
    "querystring_fallback": {
      "name": "fallback",
      "in": "query",
      "description": "Acceptable fallback options for cell and WLAN positioning. Values 'area' and 'any' apply to cell based positioning, and value 'singleWifi' applies to WLAN based positioning. They may both be combined in the same request.\nBy default cell based positioning returns cell tower level location estimates only. If you allow a WGS-84 compliant geocoordinate location estimate based on LAC, RNC, TAC, NID, or RZ areas, use the fallback=area setting. If you use the fallback=any setting, the service uses all available cell fallback methods and therefore the location estimate in the response may be at the MNC, SID, or MCC level.\nFor privacy reasons precise positioning based on a single WLAN AP is not possible. You can use the fallback=singleWifi setting to allow less accurate positioning based on a single WLAN AP. In that case the center location of the position estimate will be deviated and the reported accuracy radius will be larger.\n",
      "type": "string",
      "enum": [
        "any",
        "area",
        "singleWifi"
      ],
      "required": false
    },
    "querystring_desired": {
      "name": "desired",
      "description": "Comma-separated list of additional data fields that the service should include in the response if data is available. The query parameter supports the value 'altitude'.",
      "in": "query",
      "type": "string",
      "enum": [
        "altitude"
      ],
      "required": false
    },
    "querystring_required": {
      "name": "required",
      "description": "Comma-separated list of additional data fields that the service should include in the response. If the data is not available, the response contains an error message. The query parameter supports the value 'altitude'.",
      "in": "query",
      "type": "string",
      "enum": [
        "altitude"
      ],
      "required": false
    },
    "querystring_confidence": {
      "name": "confidence",
      "description": "Confidence level in percent for the accuracy/uncertainty in the location estimate response. If not specified, the default is 68 (this corresponds to a 68% probability that the true position is within the accuracy/uncertainty radius of the location estimate: the higher the number, the greater the confidence level).",
      "in": "query",
      "type": "integer",
      "required": false,
      "minimum": 50,
      "maximum": 99
    },
    "querystring_app_id": {
      "name": "app_id",
      "description": "A 20-byte Base64 URL-safe encoded string used for the authentication of the client application. If you use the app ID/app code option, you need to include an app_id and app_code with every request. For further details, see [Acquiring Credentials](https://dv.developer.here.com/documentation/positioning/dev_guide/topics/credentials-auth-options.html). Required unless authentication token or an API Key provided in Authorization header. Supported by host https://pos.api.here.com.\n",
      "in": "query",
      "type": "string",
      "required": false
    },
    "querystring_app_code": {
      "name": "app_code",
      "description": "A 20-byte Base64 URL-safe encoded string used for the authentication of the client application. If you use the app ID/app code option, you need to include an app_id and app_code with every request. For further details, see [Acquiring Credentials](https://dv.developer.here.com/documentation/positioning/dev_guide/topics/credentials-auth-options.html). Required unless authentication token or an API Key provided in Authorization header. Supported by host https://pos.api.here.com.\n",
      "in": "query",
      "type": "string",
      "required": false
    },
    "querystring_api_key": {
      "name": "apiKey",
      "description": "A 43-byte Base64 URL-safe encoded string used for the authentication of the client application. As a logged in user, you can generate it at your [Projects](https://developer.here.com/projects). API Keys never expire but you can invalidate your API Keys at any time. You cannot have more than two API Keys for one app at the same time. You must include an apikey with every request. Required unless authentication token provided in Authorization header. Supported by host https://pos.ls.hereapi.com.\n",
      "in": "query",
      "type": "string",
      "required": false
    },
    "header_content_encoding_gzip": {
      "name": "Content-Encoding",
      "description": "Indicates the data in the body is gzip encoded. Value must be 'gzip'.",
      "in": "header",
      "type": "string",
      "enum": [
        "gzip"
      ],
      "required": false
    },
    "header_content_type_json": {
      "name": "Content-Type",
      "description": "Indicates the media-type of the request body. Value must be 'application/json'.",
      "in": "header",
      "type": "string",
      "enum": [
        "application/json"
      ],
      "required": true
    },
    "header_authorization_bearer": {
      "description": "HERE Account bearer token. Required unless app_id and app_code, or an API Key provided in the query string parameters. Supported by hosts https://pos.api.here.com and https://pos.ls.hereapi.com.",
      "name": "authorization",
      "in": "header",
      "type": "string",
      "required": false
    },
    "body_observations_locate": {
      "name": "observations_locate",
      "description": "Request body containing cell and/or WLAN measurement data",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/observations_locate"
      }
    }
  },
  "basePath": "/positioning/v1",
  "paths": {
    "/locate": {
      "post": {
        "description": "Request WGS-84 compliant geocoordinates for a location based on 2G/3G/4G cell and/or WLAN measurements.",
        "summary": "Locate",
        "parameters": [
          {
            "$ref": "#/parameters/querystring_fallback"
          },
          {
            "$ref": "#/parameters/querystring_desired"
          },
          {
            "$ref": "#/parameters/querystring_required"
          },
          {
            "$ref": "#/parameters/querystring_confidence"
          },
          {
            "$ref": "#/parameters/querystring_app_id"
          },
          {
            "$ref": "#/parameters/querystring_app_code"
          },
          {
            "$ref": "#/parameters/querystring_api_key"
          },
          {
            "$ref": "#/parameters/header_authorization_bearer"
          },
          {
            "$ref": "#/parameters/header_content_encoding_gzip"
          },
          {
            "$ref": "#/parameters/header_content_type_json"
          },
          {
            "$ref": "#/parameters/body_observations_locate"
          }
        ],
        "responses": {
          "200": {
            "description": "Request processed successfully and a WGS-84 compliant geocoordinate location estimate was included in the response.",
            "schema": {
              "$ref": "#/definitions/response_success_locate"
            }
          },
          "400": {
            "description": "The request is malformed. Check the message in the response for additional troubleshooting information. The URL query parameters or the JSON POST body in the request is invalid.",
            "schema": {
              "$ref": "#/definitions/response_error"
            },
            "examples": {
              "application/json": {
                "error": {
                  "code": 400,
                  "message": "Bad Request",
                  "description": "'mnc' must be less than or equal to 999"
                }
              }
            }
          },
          "401": {
            "description": "Authentication has failed due to incorrect credentials. Check your app_id and app_code.",
            "schema": {
              "$ref": "#/definitions/response_error"
            },
            "examples": {
              "application/json": {
                "error": {
                  "code": 401,
                  "message": "Unauthorized",
                  "description": "The request is missing the app_id and app_code parameters. They must both be passed as query parameters. If you do not have app_id and app_code, please obtain them through your customer representative or at http://developer.here.com/myapps."
                }
              }
            }
          },
          "403": {
            "description": "Authorization has failed. Access is not allowed with the app_id and app_code you provided, or missing or incorrect API Key, or missing or incorrect Access Token in the request. For more information, see [Acquiring Credentials](https://dv.developer.here.com/documentation/positioning/dev_guide/topics/credentials-auth-options.html).",
            "schema": {
              "$ref": "#/definitions/response_error"
            },
            "examples": {
              "application/json": {
                "error": {
                  "code": 403,
                  "message": "Forbidden",
                  "description": "These credentials do not authorize access. Please contact your customer representative or submit a request here https://developer.here.com/contact-us to upgrade your account. You can also get valid credentials by registering for a free trial license on https://developer.here.com."
                }
              }
            }
          },
          "404": {
            "description": "The values provided in the request cannot produce any content for the response. The location of the WLANs and cells in the request is unknown or the locations of the radio measurements are so widely scattered that the location cannot be determined. Make sure that the network measurements are correct and consistent. Try allowing fallbacks 'area' or 'any' for cell positioning and 'singleWifi' for WLAN positioning.\n",
            "schema": {
              "$ref": "#/definitions/response_error"
            },
            "examples": {
              "application/json": {
                "error": {
                  "code": 404,
                  "message": "Not Found",
                  "description": "Position not found"
                }
              }
            }
          },
          "405": {
            "description": "Method not allowed. Only POST is supported.",
            "schema": {
              "$ref": "#/definitions/response_error"
            },
            "examples": {
              "application/json": {
                "error": {
                  "code": 405,
                  "message": "Not supported",
                  "description": "Only HTTP POST method supported"
                }
              }
            }
          },
          "500": {
            "description": "An unexpected server error has occurred, try again later.",
            "schema": {
              "$ref": "#/definitions/response_error"
            },
            "examples": {
              "application/json": {
                "error": {
                  "code": 500,
                  "message": "Internal Server Error",
                  "description": "Something unexpected happened. System administrators have been notified about the problem. Please try again later."
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "response_success_locate": {
      "description": "Object wrapper for the response to a location request.",
      "type": "object",
      "required": [
        "location"
      ],
      "properties": {
        "location": {
          "$ref": "#/definitions/position_locate"
        }
      }
    },
    "response_error": {
      "description": "Object wrapper for the error response to a request.",
      "type": "object",
      "required": [
        "error"
      ],
      "properties": {
        "error": {
          "description": "Object containing information about the error that happened",
          "type": "object",
          "required": [
            "code",
            "statusMessage"
          ],
          "properties": {
            "code": {
              "description": "Same as the HTTP response status code",
              "type": "integer"
            },
            "statusMessage": {
              "description": "Same as the HTTP status message",
              "type": "string"
            },
            "description": {
              "description": "More detailed message",
              "type": "string"
            }
          }
        }
      },
      "example": {
        "error": {
          "code": 400,
          "message": "Bad Request",
          "description": "'mnc' must be less than or equal to 999"
        }
      }
    },
    "position_locate": {
      "description": "Object containing information on a location where a measurement was taken.",
      "type": "object",
      "required": [
        "lat",
        "lng",
        "accuracy"
      ],
      "properties": {
        "lat": {
          "description": "Latitude in WGS-84 format, decimal representation ranging from -90 to 90.",
          "type": "number",
          "minimum": -90,
          "maximum": 90,
          "example": 61.4706194
        },
        "lng": {
          "description": "Longitude in WGS-84 format, decimal representation ranging from -180 to 180.",
          "type": "number",
          "minimum": -180,
          "maximum": 180,
          "example": 23.72265816
        },
        "accuracy": {
          "description": "Uncertainty circle radius in meters (degree of confidence according to the 'confidence' parameter).",
          "type": "number",
          "minimum": 1,
          "example": 829
        },
        "alt": {
          "description": "Altitude in meters (referenced to the WGS-84 ellipsoid) negative or positive.",
          "type": "integer",
          "example": 142
        },
        "altaccuracy": {
          "description": "Uncertainty of the altitude estimate in meters (degree of confidence according to the 'confidence' parameter).",
          "type": "integer",
          "minimum": 1,
          "example": 20
        }
      },
      "example": {
        "lat": 61.4706194,
        "lng": 23.72265816,
        "accuracy": 829,
        "alt": 142,
        "altaccuracy": 20
      }
    },
    "observations_locate": {
      "description": "Object wrapping the location data submitted in a request for a position. At least one gsm, wcdma, tdscdma, lte, cdma, or wlan elements is required. The elements must be unique within the request.",
      "properties": {
        "client": {
          "$ref": "#/definitions/client_info"
        },
        "gsm": {
          "description": "GSM cells (GERAN)",
          "type": "array",
          "maxItems": 16,
          "items": {
            "$ref": "#/definitions/cell_gsm_locate"
          }
        },
        "wcdma": {
          "description": "WCDMA cells (UTRA-FDD, 3G UMTS)",
          "type": "array",
          "maxItems": 16,
          "items": {
            "$ref": "#/definitions/cell_wcdma_locate"
          }
        },
        "tdscdma": {
          "description": "TD-SCDMA cell (UTRA-TDD, 3G UMTS TDD)",
          "type": "array",
          "maxItems": 16,
          "items": {
            "$ref": "#/definitions/cell_tdscdma_locate"
          }
        },
        "lte": {
          "description": "LTE cells (E-UTRA, 4G)",
          "type": "array",
          "maxItems": 16,
          "items": {
            "$ref": "#/definitions/cell_lte_locate"
          }
        },
        "cdma": {
          "description": "CDMA cells",
          "type": "array",
          "maxItems": 16,
          "items": {
            "$ref": "#/definitions/cell_cdma_locate"
          }
        },
        "wlan": {
          "description": "WLAN access points",
          "type": "array",
          "maxItems": 256,
          "items": {
            "$ref": "#/definitions/wlan_locate"
          }
        }
      },
      "example": {
        "client": {
          "manufacturer": "Lemon",
          "model": "Flagship X1",
          "name": "FinderApp",
          "version": "2.0.31"
        },
        "lte": [
          {
            "mcc": 262,
            "mnc": 2,
            "cid": 2898945
          }
        ],
        "wlan": [
          {
            "mac": "F4-55-95-11-2C-C1"
          }
        ]
      }
    },
    "client_info": {
      "description": "Information about the client",
      "type": "object",
      "required": [
        "manufacturer",
        "model",
        "name",
        "version"
      ],
      "properties": {
        "manufacturer": {
          "description": "Manufacturer of the device (hardware)",
          "type": "string",
          "minLength": 2,
          "maxLength": 50,
          "example": "Lemon"
        },
        "model": {
          "description": "Model of the device (hardware)",
          "type": "string",
          "minLength": 1,
          "maxLength": 50,
          "example": "Flagship X1"
        },
        "firmware": {
          "description": "Device firmware version information",
          "type": "string",
          "minLength": 1,
          "maxLength": 150,
          "example": "G506FXX453J1"
        },
        "platform": {
          "description": "Software platform information of the device, for example operating system name and version.",
          "type": "string",
          "minLength": 3,
          "maxLength": 50,
          "example": "Android 7.0"
        },
        "name": {
          "description": "Name of the client software accessing the HERE API",
          "type": "string",
          "minLength": 3,
          "maxLength": 50,
          "example": "FinderApp"
        },
        "version": {
          "description": "Version of the client software in format X.Y.Z, where X [0..255] is a major, Y [0..255] is a minor, and Z [0..65535] is a build version number. Increase the version/build number for each release of the client.",
          "type": "string",
          "minLength": 3,
          "maxLength": 13,
          "example": "2.0.31"
        }
      },
      "example": {
        "manufacturer": "Lemon",
        "model": "Flagship X1",
        "name": "FinderApp",
        "version": "2.0.31"
      }
    },
    "cell_gsm_locate": {
      "description": "GSM measurement",
      "type": "object",
      "required": [
        "mcc",
        "mnc",
        "lac",
        "cid"
      ],
      "properties": {
        "mcc": {
          "description": "Mobile Country Code",
          "type": "integer",
          "minimum": 200,
          "maximum": 999,
          "example": 262
        },
        "mnc": {
          "description": "Mobile Network Code",
          "type": "integer",
          "minimum": 0,
          "maximum": 999,
          "example": 1
        },
        "lac": {
          "description": "Location Area Code",
          "type": "integer",
          "minimum": 1,
          "maximum": 65535,
          "example": 5126
        },
        "cid": {
          "description": "Cell Identifier, 16 bits. Mcc+mnc+lac+cid uniquely identifies the GSM cell.",
          "type": "integer",
          "minimum": 0,
          "maximum": 65535,
          "example": 16504
        },
        "ta": {
          "description": "Timing advance (Optional). Expressed in the units of GSM bits equaling to 48/13 Î¼s ~ 1107 meters.",
          "type": "integer",
          "minimum": 0,
          "maximum": 63,
          "example": 3
        },
        "rxlevel": {
          "description": "Received Signal power (dBm) (Optional). Power less than -110dBm should be mapped to -110. Power greater than -25dBm should be mapped to -25.",
          "type": "integer",
          "minimum": -110,
          "maximum": -25,
          "example": -78
        },
        "nmr": {
          "description": "Network measurements (Optional)",
          "type": "array",
          "maxItems": 16,
          "items": {
            "$ref": "#/definitions/cell_gsm_nmr"
          },
          "example": [
            {
              "bsic": "6",
              "bcch": "82"
            }
          ]
        }
      },
      "example": {
        "mcc": 262,
        "mnc": 1,
        "lac": 5126,
        "cid": 16504,
        "nmr": [
          {
            "bsic": "6",
            "bcch": "82"
          },
          {
            "bsic": "7",
            "bcch": "85"
          },
          {
            "bsic": "12",
            "bcch": "93"
          },
          {
            "bsic": "13",
            "bcch": "88"
          },
          {
            "bsic": "19",
            "bcch": "88"
          }
        ]
      }
    },
    "cell_gsm_nmr": {
      "description": "GSM Network measurement",
      "type": "object",
      "required": [
        "bsic",
        "bcch"
      ],
      "properties": {
        "bsic": {
          "description": "Base Station Identity Code (for instance, color code)",
          "type": "integer",
          "minimum": 0,
          "maximum": 63,
          "example": 6
        },
        "bcch": {
          "description": "Broadcast Control Channel (Synonymous to ARFCN = Absolute Radio Frequency Channel)",
          "type": "integer",
          "minimum": 0,
          "maximum": 1023,
          "example": 82
        },
        "rxlevel": {
          "description": "Received Signal power (dBm) (Optional). Power less than -110dBm should be mapped to -110. Power greater than -25dBm should be mapped to -25.",
          "type": "integer",
          "minimum": -110,
          "maximum": -25,
          "example": -77
        },
        "lac": {
          "description": "Location Area Code (Optional)",
          "type": "integer",
          "minimum": 1,
          "maximum": 65535,
          "example": 5126
        },
        "cid": {
          "description": "Cell Identifier (Optional)",
          "type": "integer",
          "minimum": 0,
          "maximum": 65535,
          "example": 16503
        }
      },
      "example": {
        "bsic": "6",
        "bcch": "82"
      }
    },
    "cell_wcdma_locate": {
      "description": "WCDMA measurement",
      "type": "object",
      "required": [
        "mcc",
        "mnc",
        "cid"
      ],
      "properties": {
        "mcc": {
          "description": "Mobile Country Code",
          "type": "integer",
          "minimum": 200,
          "maximum": 999,
          "example": 262
        },
        "mnc": {
          "description": "Mobile Network Code",
          "type": "integer",
          "minimum": 0,
          "maximum": 999,
          "example": 7
        },
        "lac": {
          "description": "Location Area Code (Optional)",
          "type": "integer",
          "minimum": 1,
          "maximum": 65535,
          "example": 12345
        },
        "cid": {
          "description": "UTRAN Cell Identifier, 28 bits (12 bits RNC and 16 bits Cell id). Mcc+mnc+cid uniquely identifies the WCDMA cell, lac is optional.",
          "type": "integer",
          "minimum": 0,
          "maximum": 268435455,
          "example": 14674663
        },
        "nmr": {
          "description": "Network measurements (Optional). Maximum of 8 distinct uarfcndl frequencies.",
          "type": "array",
          "maxItems": 32,
          "items": {
            "$ref": "#/definitions/cell_wcdma_nmr"
          },
          "example": [
            {
              "uarfcndl": 10786,
              "psc": 149
            },
            {
              "uarfcndl": 10762,
              "psc": 211
            }
          ]
        }
      },
      "example": {
        "mcc": 262,
        "mnc": 7,
        "cid": 14674663,
        "nmr": [
          {
            "uarfcndl": 10786,
            "psc": 149
          },
          {
            "uarfcndl": 10762,
            "psc": 211
          }
        ]
      }
    },
    "cell_wcdma_nmr": {
      "description": "WCDMA Network measurement",
      "type": "object",
      "required": [
        "uarfcndl",
        "psc"
      ],
      "properties": {
        "uarfcndl": {
          "description": "Downlink frequency of a UTRA-FDD Serving Cell",
          "type": "integer",
          "minimum": 0,
          "maximum": 16383,
          "example": 10786
        },
        "psc": {
          "description": "Primary Scrambling Code (Primary CPICH, Primary Control Pilot Channel)",
          "type": "integer",
          "minimum": 0,
          "maximum": 511,
          "example": 149
        },
        "cid": {
          "description": "UTRAN Cell Identifier (uc-id) (Optional)",
          "type": "integer",
          "minimum": 0,
          "maximum": 268435455,
          "example": 14674662
        },
        "rscp": {
          "description": "Received Signal Code Power = RSCP (dBm) (Optional). Power less than -120dBm should be mapped to -120. Power greater than -25dBm should be mapped to -25.",
          "type": "integer",
          "minimum": -120,
          "maximum": -25,
          "example": -80
        },
        "pathloss": {
          "description": "UTRAN path loss (dB) (Optional).",
          "type": "integer",
          "minimum": 46,
          "maximum": 158,
          "example": 90
        }
      },
      "example": {
        "uarfcndl": 10786,
        "psc": 149
      }
    },
    "cell_tdscdma_locate": {
      "description": "TD-SCDMA measurement",
      "type": "object",
      "required": [
        "mcc",
        "mnc",
        "cid"
      ],
      "properties": {
        "mcc": {
          "description": "Mobile Country Code",
          "type": "integer",
          "minimum": 200,
          "maximum": 999,
          "example": 460
        },
        "mnc": {
          "description": "Mobile Network Code",
          "type": "integer",
          "minimum": 0,
          "maximum": 999,
          "example": 1
        },
        "lac": {
          "description": "Location Area Code (Optional)",
          "type": "integer",
          "minimum": 1,
          "maximum": 65535,
          "example": 1
        },
        "cid": {
          "description": "UTRAN Cell Identifier, 28 bits (12 bits RNC and 16 bits Cell id). Mcc+mnc+cid uniquely identifies the TDSCDMA cell, lac is optional.",
          "type": "integer",
          "minimum": 0,
          "maximum": 268435455,
          "example": 18563770
        },
        "ta": {
          "description": "Timing advance (Optional). Round-Trip distance presented in the units of 4*c/7.68e6 ~156 meters. That is, the scaling factor is 4 times the chip length at chip rate of 7.68 Mchips/s. Note that at chip rates 1.28 Mchips/s and 3.84 Mchips/s you need to scale according to chip length of 7.68 Mchips/s, that is, multiply by 6 or 2 if needed.",
          "type": "integer",
          "minimum": 0,
          "maximum": 1530,
          "example": 20
        },
        "nmr": {
          "type": "array",
          "description": "Network measurements (Optional). Maximum of 8 distinct uarfcn frequencies.",
          "maxItems": 32,
          "items": {
            "$ref": "#/definitions/cell_tdscdma_nmr"
          },
          "example": [
            {
              "uarfcn": 10100,
              "cellparams": 86
            },
            {
              "uarfcn": 10121,
              "cellparams": 14
            }
          ]
        }
      },
      "example": {
        "mcc": 460,
        "mnc": 0,
        "cid": 18563770,
        "nmr": [
          {
            "uarfcn": 10100,
            "cellparams": 86
          },
          {
            "uarfcn": 10121,
            "cellparams": 14
          }
        ]
      }
    },
    "cell_tdscdma_nmr": {
      "description": "TD-SCDMA Network measurement",
      "type": "object",
      "required": [
        "uarfcn",
        "cellparams"
      ],
      "properties": {
        "uarfcn": {
          "description": "Carrier frequency of a UTRA-TDD Serving Cell",
          "type": "integer",
          "minimum": 0,
          "maximum": 16383,
          "example": 10100
        },
        "cellparams": {
          "description": "Cell Parameters ID (CDMA Spreading Code ID)",
          "type": "integer",
          "minimum": 0,
          "maximum": 127,
          "example": 86
        },
        "cid": {
          "description": "Cell Identifier (uc-id) (Optional)",
          "type": "integer",
          "minimum": 0,
          "maximum": 268435455,
          "example": 18563772
        },
        "rscp": {
          "description": "Received Signal Code Power = RSCP (dBm) (Optional, you must specify a value for this item when you specify a value for pathloss). Power less than -120dBm should be mapped to -120. Power greater than -25dBm should be mapped to -25.",
          "type": "integer",
          "minimum": -120,
          "maximum": -25,
          "example": -50
        },
        "pathloss": {
          "description": "UTRAN path loss (dB) (Optional, you must specify a value for this item when you specify a value for rscp).",
          "type": "integer",
          "minimum": 46,
          "maximum": 158,
          "example": 80
        }
      },
      "example": {
        "uarfcn": 10100,
        "cellparams": 86
      }
    },
    "cell_lte_locate": {
      "description": "LTE measurement",
      "type": "object",
      "required": [
        "mcc",
        "mnc",
        "cid"
      ],
      "properties": {
        "mcc": {
          "description": "Mobile Country Code",
          "type": "integer",
          "minimum": 200,
          "maximum": 999,
          "example": 262
        },
        "mnc": {
          "description": "Mobile Network Code",
          "type": "integer",
          "minimum": 0,
          "maximum": 999,
          "example": 2
        },
        "tac": {
          "description": "Tracking Area Code (Optional)",
          "type": "integer",
          "minimum": 0,
          "maximum": 65535,
          "example": 1
        },
        "cid": {
          "description": "E-UTRA Cell Identifier, 28 bits (20 bits eNodeB and 8 bits Cell id). Mcc+mnc+cid uniquely identifies the LTE cell, tac is optional.",
          "type": "integer",
          "minimum": 0,
          "maximum": 268435455,
          "example": 2898945
        },
        "ta": {
          "description": "Timing Advance (Optional). Expressed in the units of 16*Ts (16 Basic time units) = 16/(15000*2048) seconds ~ 156meters. For reference see TS 36.213 and 36.211.",
          "type": "integer",
          "minimum": 0,
          "maximum": 1282,
          "example": 40
        },
        "rsrp": {
          "description": "Reference Signal Received Power = RSRP (dBm) (Optional, you must specify a value for this item when you specify a value for rsrq). Power less than -140dBm should be mapped to -140. Power greater than -44dBm should be mapped to -44.",
          "type": "integer",
          "minimum": -140,
          "maximum": -44,
          "example": -95
        },
        "rsrq": {
          "description": "Reference Signal Received Quality = RSRQ (dB) (Optional). Values less than -19.5dB should be mapped to -19.5, and values greater than -3dB should be mapped to -3dB.",
          "type": "number",
          "minimum": -19.5,
          "maximum": -3,
          "example": -12
        },
        "nmr": {
          "description": "LTE Network measurements (Optional)",
          "type": "array",
          "maxItems": 16,
          "items": {
            "$ref": "#/definitions/cell_lte_nmr"
          },
          "example": [
            {
              "earfcn": 6300,
              "pci": 237
            },
            {
              "earfcn": 6300,
              "pci": 442
            }
          ]
        }
      },
      "example": {
        "mcc": 262,
        "mnc": 2,
        "cid": 2898945,
        "nmr": [
          {
            "earfcn": 6300,
            "pci": 237
          },
          {
            "earfcn": 6300,
            "pci": 442
          }
        ]
      }
    },
    "cell_lte_nmr": {
      "description": "LTE Network measurement",
      "type": "object",
      "required": [
        "pci",
        "earfcn"
      ],
      "properties": {
        "pci": {
          "description": "Physical Cell Identity",
          "type": "integer",
          "minimum": 0,
          "maximum": 503,
          "example": 237
        },
        "earfcn": {
          "description": "Evolved Absolute Radio Frequency Channel",
          "type": "integer",
          "minimum": 0,
          "maximum": 65535,
          "example": 6300
        },
        "cid": {
          "description": "E-UTRA Cell Identifier (Optional)",
          "type": "integer",
          "minimum": 0,
          "maximum": 268435455,
          "example": 2898945
        },
        "rsrp": {
          "description": "Reference Signal Received Power = RSRP (dBm) (Optional, you must specify a value for this item when you specify a value for rsrq). Power less than -140dBm should be mapped to -140. Power greater than -44dBm should be mapped to -44.",
          "type": "integer",
          "minimum": -140,
          "maximum": -44,
          "example": -95
        },
        "rsrq": {
          "description": "Reference Signal Received Quality = RSRQ (dB) (Optional). Values less than -19.5dB should be mapped to -19.5, and values greater than -3dB should be mapped to -3dB.",
          "type": "number",
          "minimum": -19.5,
          "maximum": -3,
          "example": -12
        }
      },
      "example": {
        "earfcn": 6300,
        "pci": 237
      }
    },
    "cell_cdma_locate": {
      "description": "CDMA measurement",
      "type": "object",
      "required": [
        "sid",
        "nid",
        "bsid"
      ],
      "properties": {
        "sid": {
          "description": "System Id, SID",
          "type": "integer",
          "minimum": 1,
          "maximum": 32767,
          "example": 4162
        },
        "nid": {
          "description": "Network Id, NID",
          "type": "integer",
          "minimum": 0,
          "maximum": 65535,
          "example": 10
        },
        "rz": {
          "description": "Registration zone (Optional)",
          "type": "integer",
          "minimum": 0,
          "maximum": 4095,
          "example": 1234
        },
        "bsid": {
          "description": "Base Station ID, BID",
          "type": "integer",
          "minimum": 0,
          "maximum": 65535,
          "example": 8583
        },
        "pnoffset": {
          "description": "Pseudonoise offset (Optional, you must specify a value for this item when you specify a value for channel)",
          "type": "integer",
          "minimum": 0,
          "maximum": 511,
          "example": 367
        },
        "channel": {
          "description": "CDMA channel frequency (Optional, you must specify a value for this item when you specify a value for pnoffset)",
          "type": "integer",
          "minimum": 0,
          "maximum": 2047,
          "example": 1
        },
        "pilotpower": {
          "description": "Pilot Power (dBm) (Optional). If Pilot Power is not available directly, it needs to be calculated from Total Power in the band and Pilot Strength with respect to the Total Power. Pilot power less than -142dBm should be mapped to -142. Pilot power greater than -49dBm should be mapped to -49.",
          "type": "integer",
          "minimum": -142,
          "maximum": -49,
          "example": -96
        },
        "nmr": {
          "description": "CDMA Network measurements (Optional)",
          "type": "array",
          "maxItems": 32,
          "items": {
            "$ref": "#/definitions/cell_cdma_nmr"
          },
          "example": [
            {
              "channel": 0,
              "pnoffset": 357
            },
            {
              "channel": 0,
              "pnoffset": 366
            }
          ]
        }
      },
      "example": {
        "sid": 4162,
        "nid": 10,
        "bsid": 8583,
        "nmr": [
          {
            "channel": 0,
            "pnoffset": 357
          },
          {
            "channel": 0,
            "pnoffset": 366
          }
        ]
      }
    },
    "cell_cdma_nmr": {
      "description": "CDMA Network measurement",
      "type": "object",
      "required": [
        "pnoffset",
        "channel"
      ],
      "properties": {
        "pnoffset": {
          "description": "Pseudonoise offset",
          "type": "integer",
          "minimum": 0,
          "maximum": 511,
          "example": 357
        },
        "channel": {
          "description": "CDMA channel frequency",
          "type": "integer",
          "minimum": 0,
          "maximum": 2047,
          "example": 1
        },
        "bsid": {
          "description": "Base Station ID (Optional)",
          "type": "integer",
          "minimum": 0,
          "maximum": 65535,
          "example": 8584
        },
        "pilotpower": {
          "description": "Pilot Power (dBm) (Optional). If Pilot Power is not available directly, it needs to be calculated from Total Power in the band and Pilot Strength with respect to the Total Power. Pilot power less than -142dBm should be mapped to -142. Pilot power greater than -49dBm should be mapped to -49.",
          "type": "integer",
          "minimum": -142,
          "maximum": -49,
          "example": -99
        }
      },
      "example": {
        "channel": 0,
        "pnoffset": 357
      }
    },
    "wlan_locate": {
      "description": "WLAN measurement",
      "type": "object",
      "required": [
        "mac"
      ],
      "properties": {
        "mac": {
          "description": "The MAC address of the WLAN access point. MAC-48 address with colon (:) or hyphen (-) separators, upper or lower case hex digits. Note that if the SSID contains postfix \"_nomap\", the AP should not be used for positioning. For privacy reasons positioning based on a single WLAN AP is not possible; there has to be at least one other matching wlan or cell. Alternative you can allow fallbacks to less accurate single WLAN AP location estimates by using the setting fallback=singleWifi.\n",
          "type": "string",
          "example": "8C-1A-BF-20-66-AD"
        },
        "powrx": {
          "description": "Received signal level (dBm) at the terminal (Optional)",
          "type": "integer",
          "minimum": -128,
          "maximum": 0,
          "example": -76
        }
      },
      "example": {
        "mac": "8C-1A-BF-20-66-AD"
      }
    }
  }
}